const INTEL_DATA = {
  meta: {
    date: "2026.05.03",
    weekday: "週日",
    weekday_en: "Sunday",
    issue: 3,
  },

  priority: {
    level: "P1",
    title: "GPT-5.3 vs GPT-5.4 引用行為大分歧：同一問題、7% 重疊、需要兩套完全不同的 GEO 策略",
    body: "Writesonic 研究（Mar 2026，50 個 prompt）揭露：GPT-5.3 Instant（免費預設）92% 引用來自 Forbes、TechRadar 等第三方媒體，品牌官網只佔 8%；GPT-5.4 Thinking 則 56% 直接引用品牌官網，使用 site: 運算子主動搜尋品牌頁面。兩個模型對同一問題的引用重疊率平均僅 7%，50 個 prompt 中有 22 個重疊率為零。SEO 專家 Chris Long 稱此為「劃時代改變」。⚠️ 研究樣本規模僅 50 個 prompt，且 GPT-5.5 已於 4/23 發布，模型環境仍在快速演變中。",
  },

  cards: [
    {
      domain: "GEO",
      category: "strategy",
      credibility: "research",
      title: "GPT 模型分裂：GPT-5.3 靠媒體報導、GPT-5.4 直接抓品牌網站，兩套平行策略缺一不可",
      body: "Writesonic ChatGPT 引用研究（Mar 2026，119 段對話，50 個 prompt，7,896 筆網路結果）核心發現：\n\nGPT-5.3 Instant（免費預設）行為：送出一個廣泛查詢 → 返回搜尋前幾名 → 92% 引用 Forbes、TechRadar、Tom's Guide、Reddit 等第三方媒體，品牌官網僅佔 8%（前代 GPT-5.2 為 22%，下降明顯）。傳統 SEO 有 47% 影響力，因為 47% 的 GPT-5.3 引用來自 Google 排名網域。\n\nGPT-5.4 Thinking（付費）行為：單一 prompt 平均分解為 8.5 個子查詢，且直接使用 site: 運算子搜尋品牌網域 — 這是前所未有的行為。56% 直接引用品牌官網；75% 的引用網域甚至不出現在 Google/Bing 同查詢的搜尋結果中，代表它從訓練資料認識品牌、再主動抓取頁面。\n\n兩模型重疊率：50 個 prompt 平均引用重疊僅 7%；22 個 prompt 重疊率為零。品牌不能只優化一個模型。\n\n⚠️ 此研究由 Writesonic（商業工具公司）執行，樣本僅 50 個 prompt；GPT-5.5 於 4/23 發布後行為尚待驗證。",
      action: "立即在 ChatGPT 免費版（GPT-5.3）和付費 Thinking 模式分別測試 5–10 個品牌核心查詢，比對引用來源。若 GPT-5.3 不引用品牌官網 → 投資數位 PR 進入第三方媒體；若 GPT-5.4 抓不到品牌頁面 → 優先修復 SSR 和頁面結構。",
      full: true,
    },
    {
      domain: "AEO",
      category: "execution",
      credibility: "research",
      title: "Fan-Out Effect 研究：最佳頁面規格—500–2,000 字、聚焦標題、JSON-LD，DA 無關",
      body: "AirOps × Kevin Indig 研究（Apr 2026，16,851 查詢、353,799 頁面）建立迄今最大規模的 ChatGPT 引用機制數據集，提供可直接操作的頁面規格：\n\n① 檢索排名是最強預測因子：第 1 名引用率 58%，第 10 名僅 14%（4 倍差距）。\n② 標題語意匹配是最強頁面內信號：cosine similarity ≥ 0.9 頁面引用率 41%，弱匹配僅 30%。\n③ 終極指南策略反效果：涵蓋 26–50% fan-out 子查詢（38.2%）優於涵蓋 100%（34.0%）。\n④ DA 無關甚至負相關：永遠被引用頁面平均 DA 53，從未被引用頁面 DA 56。\n⑤ JSON-LD 有獨立效果：+6.5pp，FAQPage（45.6%）、BreadcrumbList（46.2%）最佳。\n⑥ 最佳頁面規格：500–2,000 字（超過 5,000 字表現低於 500 字以下）；7–20 個子標題；FK 閱讀難度 16–17 級（大學程度）。\n\n⚠️ 僅限 ChatGPT / Bing 管道，不能直接套用 Perplexity 或 Google AI Overview。",
      action: "用這組規格審計現有核心頁面：字數超過 3,000 字考慮拆分；確認子標題 7–20 個；用 Hemingway App 確認 FK 14–17；部署 FAQPage 或 BreadcrumbList JSON-LD；確保 Bing Webmaster Tools 已提交 sitemap。",
      full: false,
    },
    {
      domain: "SEO",
      category: "strategy",
      credibility: "official",
      title: "Google Preferred Sources 全球化：用戶主動偏好首度成為 Top Stories 正式排名信號",
      body: "2026 年 4 月 30 日，Google 官方宣布 Preferred Sources 功能正式在所有支援語言全球上線（Barry Schwartz、9to5Google 同日確認，Search Engine Journal 深度報導）。此前自 2025 年推出時僅限英文。\n\n核心數據（Google 官方公布）：\n- 被標記為 Preferred Source 的網站，用戶點擊率提高 2 倍\n- 全球已有超過 200,000 個獨特網站被用戶選擇\n- 提供 16 種語言版本的可下載按鈕素材\n\n機制：用戶在 Top Stories 旁點擊星號選擇偏好來源，Google 將此信號與演算法排名並行使用，效果及於 Top Stories 與 Google Discover。\n\nSEJ 分析：這是 Google 首次將用戶主動宣告的偏好作為 Top Stories 的正式排名因素，搜尋可見性從單純的演算法競爭，加入了品牌習慣與信任競爭。⚠️ 此功能目前只影響 Top Stories 與 Discover，對一般藍色連結排名無直接效果。",
      action: "若有定期發布新聞或內容：在網站顯眼位置加入 Google 提供的「設為最愛來源」按鈕；在電子報提醒既有讀者操作；在 GSC 監控 Top Stories 印象數與 CTR 的月度變化。",
      full: false,
    },
    {
      domain: "SEO",
      category: "measurement",
      credibility: "opinion",
      title: "4 月起 Google 大規模去索引潮：SEO 社群集體回報，官方稱正常",
      body: "從 2026 年 4 月初起，SEO 社群大規模回報 Google 去索引速度異常加快。前 Google 員工 Pedro Dias 在社群媒體公開詢問，隨即引發大量業界確認（Barry Schwartz / SE Roundtable May 1 報導）。\n\n業界歸納受影響最大類型：AI 生成但未人工編輯的頁面、薄內容與重複內容、長期未更新的舊頁面、缺乏內部連結的孤立頁面、僅服務於 SEO 目的的功能性頁面。\n\nGoogle 官方回應：John Mueller 表示「我沒有看到任何異常，部分網站上升、部分下降是正常現象。」\n\n業界主流理論：AI 生成內容大量湧現後，Google 正加強索引品質篩選，主動清除無法為用戶提供獨特價值的頁面。\n\n⚠️ 這是業界觀察彙整，非 Google 官方確認的政策變動。Mueller 的回應未正面排除背景機制變化的存在。",
      action: "GSC → 索引 → 頁面，檢查「已爬取但目前未編入索引」數量是否在 4 月後顯著增加；優先審計：字數 < 300、無外部連結、超過 1 年未更新、或完全由 AI 生成未編輯的頁面。",
      full: false,
    },
    {
      domain: "GEO",
      category: "measurement",
      credibility: "research",
      title: "GPT-5.3 切換後 ChatGPT 引用域名 -20%：競爭對手減少，留下者份額更大",
      body: "Resoneo（法國 SEO 顧問）使用 Meteoria 平台，追蹤 400 個 prompt 共 14 週 27,000 筆回答，量化 2026 年 3 月初 GPT-5.3 Instant 成為預設模型後的引用版圖變化：\n\n每次回答平均引用網域：19 → 15（-20%）\n每次回答平均引用 URL：24 → 19（-21%）\nURL / 網域比率：維持 1 不變（訪問更少網站，但每站深讀）\n\nOncrawl Jérôme Salomon 獨立伺服器 log 同期確認：ChatGPT-User bot 爬取量顯著下降，部分頁面完全停止被爬取。\n\n策略意義：引用池縮小 → 被引用的網站每個拿到更大的「引用份額」。這是零和市場縮小，而非市場消失。\n\n未來：GPT-5.5（4/23 發布）的引用行為尚待實測；Resoneo 指出 GPT-5.4 Thinking 已重新引入 fan-out 搜尋模式。⚠️ 單一機構研究，已公開方法但待第三方驗證。",
      action: "在 GA4 或 Ahrefs 中，將 2026 年 3 月 1–15 日前後來自 chat.openai.com 的推薦流量做對比；若引用流量明顯下降，集中資源鞏固在少數關鍵查詢的引用地位，而非分散覆蓋面。",
      full: false,
    },
  ],

  actions: [
    {
      priority: "high",
      label: "立即",
      text: "在 ChatGPT 免費版（GPT-5.3）和付費 Thinking 模式分別測試 5–10 個品牌核心查詢，比對引用來源，判斷品牌落在哪個引用池，決定優先投入數位 PR 還是頁面結構優化。",
      tag: "GEO · 衡量",
    },
    {
      priority: "high",
      label: "本週",
      text: "GSC → 索引 → 頁面，確認「已爬取但目前未編入索引」數量是否在 4 月後異常上升；優先審計 AI 生成未編輯、薄內容、超過 1 年未更新的頁面。",
      tag: "SEO · 技術",
    },
    {
      priority: "mid",
      label: "本月",
      text: "核心頁面 AEO 審計：對照 Fan-Out 研究規格（500–2,000 字、7–20 個子標題、FK 14–17 級、FAQPage JSON-LD），找出不符合的頁面並排優先序重寫。",
      tag: "AEO · 執行",
    },
    {
      priority: "mid",
      label: "本月",
      text: "若有定期內容發布：在網站加入 Google Preferred Sources「設為最愛來源」按鈕，並在電子報通知既有讀者；監控 GSC Top Stories 印象數月度變化。",
      tag: "SEO · 執行",
    },
    {
      priority: "low",
      label: "Q2",
      text: "布局 GPT-5.3 引用管道：評估在 Forbes、業界媒體、Reddit 相關版位建立品牌曝光的數位 PR 計畫，進入 GPT-5.3 的第三方引用池；同步確認 Bing Webmaster Tools 已驗證並提交 sitemap。",
      tag: "GEO · 策略",
    },
  ],

  tracker: {
    AEO: [
      {
        cat: "On-page",
        item: "Answer-first Structure",
        note: "頁面首段直接給出答案，後段補充佐證與細節",
        update: "🆕 AirOps Fan-Out 研究（Apr 2026）：標題語意匹配是最強頁面內信號，高匹配（≥0.9）引用率 41% vs 弱匹配 30%。Growth Memo（Feb 2026）：44.2% 的 LLM 引用來自文章前 30% 文字。研究僅限 ChatGPT / Bing 管道。",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
      {
        cat: "On-page",
        item: "Schema Markup",
        note: "sameAs / about / mentions 標記建立品牌實體跨平台一致性",
        update: "🆕 AirOps Fan-Out 研究確認 JSON-LD 有獨立 +6.5pp 引用率效果，控制所有其他變數後仍顯著。FAQPage（45.6%）、BreadcrumbList（46.2%）、Organization（44.3%）效果最佳。",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
      {
        cat: "Technical",
        item: "llms.txt",
        note: "在網站根目錄放置 Markdown 格式的 AI 內容導引檔案",
        update: "OtterlyAI（Apr 2026）實驗新發現：AI 只引用 HTML 頁面，完全忽略 .md 頁面，暗示 llms.txt 的 Markdown 格式可能對引用無效。建議：llms.txt 本身保持 Markdown，但指向的目標頁面必須是 HTML。",
        trend: "stable",
        cred: "opinion",
        ref: "https://www.position.digital/blog/ai-seo-statistics/",
      },
      {
        cat: "Technical",
        item: "Robots.txt / AI 爬蟲管理",
        note: "針對 GPTBot、ClaudeBot、PerplexityBot、Google-Extended 設定爬取權限",
        update: "BuzzStream（Apr 2026）：~75% 封鎖 AI bot 的網站仍出現在 AI 引用中（訓練資料路徑）；但 ~70% 的 ChatGPT 引用來自封鎖 ChatGPT-User bot 的網站，顯示訓練與即時檢索是兩套系統。LLM bot 爬取量現為 Googlebot 的 3.6 倍（SEJ, Apr 2026）。",
        trend: "up",
        cred: "research",
        ref: "https://www.position.digital/blog/ai-seo-statistics/",
      },
      {
        cat: "Authority",
        item: "E-E-A-T",
        note: "Experience / Expertise / Authoritativeness / Trustworthiness 綜合信號",
        update: "Fan-Out Effect 研究從 AI 引用角度反面印證：DA 與引用率無正相關，永遠被引用頁面平均 DA 53 < 從未被引用頁面 DA 56。E-E-A-T 在 Google SEO 仍重要，但傳統 DA 指標在 AI 引用中失效。",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
    ],

    GEO: [
      {
        cat: "平台布局",
        item: "YouTube",
        note: "產品示範、教學影片，真人出鏡提供難以偽造的真實性訊號",
        update: "Q1 2026：YouTube 超越 Reddit 成為 LLM 第一引用來源，約佔 AI 回答的 16%（GEORaiser）。Fan-Out 研究中 YouTube DA 100 但引用率僅 2.4%，顯示高 DA 不保證引用，頁面結構仍是關鍵。",
        trend: "up",
        cred: "opinion",
        ref: "https://georaiser.com/blog/youtube-overtakes-reddit-ai-citations",
      },
      {
        cat: "平台布局",
        item: "LinkedIn（長文）",
        note: "LinkedIn 文章（非短貼文）對 B2B 品牌的 AI 引用效果顯著高於一般貼文",
        update: "LinkedIn 在 ChatGPT 引用排名中 3 個月從第 11 升至第 5（GEORaiser）。LinkedIn 文章佔 LinkedIn 所有 AI 引用的 50–66%。",
        trend: "up",
        cred: "opinion",
        ref: "https://georaiser.com/blog/youtube-overtakes-reddit-ai-citations",
      },
      {
        cat: "平台布局",
        item: "Reddit",
        note: "真實社群討論，Perplexity 與 Google AI Overview 引用來源仍有效",
        update: "Reddit 是 GPT-5.3 引用池主力（Writesonic, Mar 2026）；對 GPT-5.4 Thinking 影響力較低。Perplexity 與 Google AI Overview 的 Reddit 引用仍穩定。跨模型策略需差異化。",
        trend: "stable",
        cred: "opinion",
        ref: "https://www.bradleebartlett.com/blog/gpt-5-4-citation-study-chatgpt-who-gets-cited",
      },
      {
        cat: "平台布局",
        item: "Google AI Mode",
        note: "Google 的對話式 AI 搜尋體驗，已嵌入 Chrome 與 Android",
        update: "AI Overviews 與 AI Mode 引用來源重疊率僅 13.7%，需分別優化。93% 的 Google AI Mode 搜尋為零點擊（ALM Corp, 2026）。⚠️ 數字來源標注不完整，需審慎引用。",
        trend: "up",
        cred: "official",
        ref: "https://techcrunch.com/2026/04/16/google-now-lets-you-explore-the-web-side-by-side-with-ai-mode/",
      },
      {
        cat: "內容策略",
        item: "Fan-out 覆蓋策略",
        note: "針對 ChatGPT：26–50% 子查詢覆蓋勝過 100% 全面覆蓋，聚焦優於廣泛",
        update: "🆕 AirOps + Kevin Indig 研究（Apr 2026）確立：涵蓋 26–50% fan-out 子查詢引用率 38.2% > 100% 覆蓋 34.0%；最佳字數 500–2,000 字；最佳子標題數 7–20 個。⚠️ 僅 ChatGPT / Bing 管道。",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
      {
        cat: "量測",
        item: "AI Traffic Share / Brand Mention Rate",
        note: "追蹤品牌在各 AI 平台回答中的提及率與引用頻率",
        update: "GPT-5.3 切換後引用網域 -20%（Resoneo, Apr 2026）；GPT-5.3 與 GPT-5.4 引用來源重疊僅 7%（Writesonic）。模型升級頻繁，建議每月重新測試基準查詢；35% 的 ChatGPT 查詢觸發即時搜尋（Superlines, Apr 2026）。",
        trend: "down",
        cred: "research",
        ref: "https://www.searchenginejournal.com/chatgpt-search-is-citing-fewer-sites-data-shows/571219/",
      },
      {
        cat: "工具",
        item: "Lumar AI Visibility / Cloudflare AI 爬蟲管理",
        note: "追蹤 AI 引用並管理 AI 爬蟲存取的新工具",
        update: "🆕 Lumar 推出 AI Visibility 工具，追蹤品牌在 AI 回答中的出現率、情感傾向與引用來源。Cloudflare 新功能：自動將 GPTBot、ClaudeBot 的 canonical 標籤轉成 301 重定向，減少 AI 爬蟲讀取重複內容。",
        trend: "up",
        cred: "opinion",
        ref: "https://www.lumar.io/blog/industry-news/seo-ai-search-industry-news-april-2026/",
      },
    ],

    SEO: [
      {
        cat: "演算法",
        item: "Core Updates",
        note: "每季 1–2 次大型排名重評，著重整體網站品質訊號",
        update: "March 2026 Core Update（3/27–4/8）完成：前三名 URL 變動率 79.5%（SE Ranking）；「目的地品牌」得利、「中介站」失血模式確立（Aleyda Solis, Sistrix）。",
        trend: "stable",
        cred: "research",
        ref: "https://searchengineland.com/march-2026-google-core-update-what-changed-474397",
      },
      {
        cat: "演算法",
        item: "Spam Updates",
        note: "針對連結操控、規模化低品質內容的獨立更新",
        update: "4 月起 SEO 社群集體回報 URL 去索引速度異常加快；Google John Mueller 稱「屬正常範圍」；前 Google 員工 Pedro Dias 最初提出此現象。業界主流理論：AI 內容氾濫後索引品質篩選加強。⚠️ 未獲官方確認。",
        trend: "up",
        cred: "opinion",
        ref: "https://www.seroundtable.com/category/google-updates",
      },
      {
        cat: "流量",
        item: "AI Overview CTR 影響",
        note: "有 AI Overview 的查詢，傳統有機結果點擊率顯著下降",
        update: "有 AI Overview 的查詢 CTR 下降 61%（Seer Interactive, Apr 2026）；被 AI Overview 引用的頁面每印象點擊率比未引用高 120%。93% 的 Google AI Mode 搜尋為零點擊（ALM Corp）。",
        trend: "down",
        cred: "research",
        ref: "https://ahrefs.com/blog/ai-overviews-reduce-clicks-update/",
      },
      {
        cat: "排名信號",
        item: "Page-level Authority / 目的地品牌",
        note: "品牌官網、官方機構、專科媒體的「目的地價值」成為核心排名差異因子",
        update: "Fan-Out Effect 研究從 AI 引用角度印證：DA 無法預測 AI 引用。Preferred Sources（Apr 30 全球化）引入用戶主動偏好，「被記得」與「被選擇」成為 Top Stories 新競爭維度。",
        trend: "up",
        cred: "research",
        ref: "https://searchengineland.com/march-2026-google-core-update-what-changed-474397",
      },
      {
        cat: "排名信號",
        item: "Preferred Sources（用戶主動偏好信號）",
        note: "用戶主動標記偏好來源，作為 Top Stories 與 Google Discover 的正式排名信號",
        update: "🆕 2026 年 4 月 30 日全球化（所有支援語言）；被標記網站點擊率 +2 倍；200,000+ 網站已被選擇；Google 提供 16 種語言版按鈕素材（官方確認）。",
        trend: "up",
        cred: "official",
        ref: "https://searchengineland.com/google-preferred-sources-now-works-for-all-languages-476051",
      },
    ],
  },
};
