const INTEL_DATA_EN = {
  meta: {
    date: "2026.05.03",
    weekday: "週日",
    weekday_en: "Sunday",
    issue: 3,
  },

  priority: {
    level: "P1",
    title: "GPT-5.3 vs GPT-5.4 Citation Behavior Split: Same Query, 7% Overlap, Two Completely Different GEO Strategies Required",
    body: "A Writesonic study (Mar 2026, 50 prompts) found GPT-5.3 Instant (free default) sources 92% of citations from third-party media like Forbes and TechRadar, with brand websites at just 8%. GPT-5.4 Thinking (paid) cites brand websites 56% of the time, using site: operators to directly query brand domains. Average citation overlap between the two models for the same prompt is just 7% — and for 22 of 50 prompts, the overlap was exactly zero. SEO expert Chris Long called this a 'monumental' change. ⚠️ The study covers only 50 prompts from a commercial tool vendor (Writesonic); GPT-5.5 launched April 23, so model behavior continues to evolve rapidly.",
  },

  cards: [
    {
      domain: "GEO",
      category: "strategy",
      credibility: "research",
      title: "The GPT Model Split: GPT-5.3 Needs Media Coverage, GPT-5.4 Needs Your Website — Two Parallel Strategies, Neither Optional",
      body: "Writesonic ChatGPT Citation Study (Mar 2026, 119 conversations, 50 prompts, 7,896 web results analyzed) reveals fundamentally different citation behaviors by model tier:\n\nGPT-5.3 Instant (free default): Sends one broad query → surfaces top results → cites Forbes, TechRadar, Tom's Guide, Reddit and similar third-party publishers 92% of the time. Brand websites: only 8% (down from 22% in GPT-5.2). Traditional SEO still matters: 47% of GPT-5.3 citations come from Google-ranked domains.\n\nGPT-5.4 Thinking (paid): Decomposes a single prompt into an average of 8.5 sub-queries and uses site: operators to directly query brand domains — a behavior no previous ChatGPT model exhibited. 56% of citations go directly to brand websites. 75% of cited domains don't appear in Google/Bing results for the same query — the model discovers brands through training data and then actively fetches their pages.\n\nOverlap between models: Average 7% across 50 prompts; 22 prompts had zero overlap. You cannot optimize for just one model.\n\n⚠️ This study was conducted by Writesonic, a commercial tool vendor, with a 50-prompt sample. GPT-5.5 launched April 23; its citation behavior is not yet independently verified.",
      action: "Test 5–10 core brand queries in both ChatGPT free tier (GPT-5.3) and paid Thinking mode (GPT-5.4+) right now. Compare citation sources. If GPT-5.3 doesn't cite your brand site → invest in digital PR for third-party media placement. If GPT-5.4 can't parse your brand pages → fix SSR and page structure first.",
      full: true,
    },
    {
      domain: "AEO",
      category: "execution",
      credibility: "research",
      title: "Fan-Out Effect Study: Ideal Page Spec — 500–2K Words, Focused Headings, JSON-LD. DA Is Irrelevant.",
      body: "AirOps × Kevin Indig (Apr 2026, 16,851 queries, 353,799 pages) — the largest ChatGPT citation mechanism dataset to date — delivers actionable page specifications:\n\n① Retrieval rank is the dominant signal: Position 1 = 58% citation rate; Position 10 = 14%. A 4× gap no content quality alone can close.\n② Heading semantic match is the strongest on-page signal: cosine similarity ≥ 0.9 pages cite at 41%; weak match pages: 30%.\n③ The 'ultimate guide' strategy backfires: 26–50% fan-out coverage (38.2%) beats 100% coverage (34.0%).\n④ DA is slightly negatively correlated: always-cited pages average DA 53 vs. never-cited pages DA 56.\n⑤ JSON-LD has an independent +6.5pp effect: FAQPage (45.6%), BreadcrumbList (46.2%), Organization (44.3%) lead.\n⑥ Ideal page spec: 500–2,000 words (5,000+ underperforms sub-500); 7–20 H2-H4 subheadings; FK readability grade 16–17 (college level).\n\n⚠️ Results cover the ChatGPT / Bing pipeline only. Do not directly apply to Perplexity or Google AI Overview.",
      action: "Audit core pages against this spec: split pages over 3,000 words; verify 7–20 subheadings; check readability with Hemingway App (target FK 14–17); deploy FAQPage or BreadcrumbList JSON-LD; confirm Bing Webmaster Tools sitemap submission.",
      full: false,
    },
    {
      domain: "SEO",
      category: "strategy",
      credibility: "official",
      title: "Google Preferred Sources Goes Global: User Preference Becomes an Official Top Stories Ranking Signal",
      body: "On April 30, 2026, Google officially announced Preferred Sources is now available across all Google Search-supported languages globally (confirmed by Barry Schwartz / SE Roundtable and 9to5Google same day; Search Engine Journal deep-dive coverage followed). Previously limited to English since its 2025 launch.\n\nOfficial data released by Google:\n- Users are 2× more likely to click through to a site after marking it as a Preferred Source\n- More than 200,000 unique sites have already been selected globally\n- Downloadable button assets available in 16 languages for publishers\n\nMechanism: Users tap the star icon next to Top Stories to choose preferred publishers; Google uses this explicit user signal alongside algorithmic ranking, with effects reaching both Top Stories and Google Discover.\n\nSEJ analysis: This is the first time Google has formally incorporated user-declared publisher preferences as a Top Stories ranking factor — shifting search visibility from pure algorithmic competition to include brand habit and trust competition. ⚠️ This feature affects Top Stories and Discover only; no confirmed direct effect on standard blue-link rankings.",
      action: "If you publish news or regular content: add Google's 'Set as Preferred Source' button prominently on your site; notify existing subscribers via newsletter; monitor GSC Top Stories impressions and CTR month-over-month.",
      full: false,
    },
    {
      domain: "SEO",
      category: "measurement",
      credibility: "opinion",
      title: "Google Mass Deindexing Since April: SEO Community Reports Surge, Mueller Says It's Normal",
      body: "Since early April 2026, a large wave of SEO professionals has reported unusually high URL deindexing rates. The discussion was surfaced publicly by former Google employee Pedro Dias, who asked whether the community was seeing elevated random deindexing — and received immediate broad confirmation. Covered by Barry Schwartz / SE Roundtable (May 1) and reported by Search Engine Land.\n\nSite types most commonly reported as affected (community-sourced): AI-generated pages without human editing, thin and duplicate content, pages not updated for 1+ years, orphan pages with no internal links, purely functional/SEO-only pages.\n\nGoogle's official response: John Mueller stated: 'I don't see anything exceptional happening. Some sites going up and down is normal.'\n\nPrevailing industry theory: As AI-generated content floods the web at unprecedented scale, Google is applying stricter quality filtering to its index — actively removing pages that provide no unique value to users.\n\n⚠️ This is community observation, not a confirmed Google policy change. Mueller's response did not explicitly deny that background quality filtering has intensified.",
      action: "GSC → Indexing → Pages: check whether 'Crawled – currently not indexed' count has risen significantly since April. Priority audit: pages under 300 words, no external links, last updated 1+ years ago, or fully AI-generated without human editing.",
      full: false,
    },
    {
      domain: "GEO",
      category: "measurement",
      credibility: "research",
      title: "GPT-5.3 Switch Cut ChatGPT Citation Domains by 20% — Fewer Competitors, Bigger Share for Survivors",
      body: "Resoneo (French SEO consultancy) used the Meteoria AI visibility platform to monitor 400 prompts across 14 weeks (27,000 responses), quantifying the impact of GPT-5.3 Instant becoming the default ChatGPT model in early March 2026:\n\nAverage unique domains per response: 19 → 15 (−20%)\nAverage unique URLs per response: 24 → 19 (−21%)\nURLs per domain ratio: held constant at 1 (visiting fewer sites, but reading each one just as deeply)\n\nOncrawl's Jérôme Salomon independently confirmed via server log analysis: ChatGPT-User bot crawl volume dropped significantly in the same period, with some pages no longer being crawled at all.\n\nStrategic implication: A smaller citation pool means the sites that remain cited capture a larger share of each answer. This is a shrinking zero-sum game, not a disappearing market.\n\nForward uncertainty: GPT-5.5 launched April 23; citation behavior under the new model is not yet quantified. Resoneo notes GPT-5.4 Thinking reintroduces fan-out searches. ⚠️ Single-institution study; methodology is published but awaits independent replication.",
      action: "In GA4 or Ahrefs, compare referral traffic from chat.openai.com before vs. after March 1–15, 2026. If referral traffic dropped materially, concentrate resources on dominating citation in a small set of priority queries rather than trying to expand breadth.",
      full: false,
    },
  ],

  actions: [
    {
      priority: "high",
      label: "Now",
      text: "Test 5–10 core brand queries in both ChatGPT free tier (GPT-5.3) and paid Thinking mode (GPT-5.4+). Compare citation sources to determine which citation pool your brand falls into and where to invest first.",
      tag: "GEO · Measurement",
    },
    {
      priority: "high",
      label: "This Week",
      text: "GSC → Indexing → Pages: verify whether 'Crawled – currently not indexed' count has risen abnormally since April. Priority audit: AI-generated-but-unedited pages, thin content, and pages not updated in 1+ years.",
      tag: "SEO · Technical",
    },
    {
      priority: "mid",
      label: "This Month",
      text: "Run a core page AEO audit against Fan-Out study specs (500–2,000 words, 7–20 subheadings, FK grade 14–17, FAQPage JSON-LD). Identify non-compliant pages and prioritize rewrites.",
      tag: "AEO · Execution",
    },
    {
      priority: "mid",
      label: "This Month",
      text: "If you publish regular content: add Google's Preferred Sources button to your site and notify existing readers via newsletter. Monitor GSC Top Stories impressions month-over-month.",
      tag: "SEO · Execution",
    },
    {
      priority: "low",
      label: "Q2",
      text: "Build a GPT-5.3 citation pipeline: plan digital PR outreach targeting Forbes, industry media, and relevant Reddit communities to enter GPT-5.3's third-party citation pool. Also confirm Bing Webmaster Tools is verified and sitemap submitted.",
      tag: "GEO · Strategy",
    },
  ],

  tracker: {
    AEO: [
      {
        cat: "On-page",
        item: "Answer-first Structure",
        note: "Lead with the answer in the opening paragraph; substantiate and expand in the body",
        update: "🆕 AirOps Fan-Out study (Apr 2026): heading semantic match is the strongest on-page signal — high match (≥0.9) pages cite at 41% vs. 30% for weak matches. Growth Memo (Feb 2026): 44.2% of LLM citations come from the first 30% of text. ChatGPT / Bing pipeline only.",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
      {
        cat: "On-page",
        item: "Schema Markup",
        note: "sameAs / about / mentions properties establish consistent brand entity identity across the web",
        update: "🆕 AirOps Fan-Out study confirms JSON-LD has independent +6.5pp citation effect, holding after controlling for word count, headings, and DA. FAQPage (45.6%), BreadcrumbList (46.2%), Organization (44.3%) are top-performing types.",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
      {
        cat: "Technical",
        item: "llms.txt",
        note: "Markdown AI content guide file at website root, directing LLMs to priority content",
        update: "OtterlyAI (Apr 2026) experiment: AI cites only HTML pages and ignores .md pages entirely — suggesting llms.txt's Markdown format may not improve citation. Recommendation: keep llms.txt in Markdown, but ensure all linked target pages are HTML.",
        trend: "stable",
        cred: "opinion",
        ref: "https://www.position.digital/blog/ai-seo-statistics/",
      },
      {
        cat: "Technical",
        item: "Robots.txt / AI Crawler Management",
        note: "Setting crawl permissions for GPTBot, ClaudeBot, PerplexityBot, Google-Extended",
        update: "BuzzStream (Apr 2026): ~75% of sites blocking AI bots still appear in AI citations (training data pathway); ~70% of ChatGPT citations come from sites blocking ChatGPT-User bot, confirming training and live retrieval are separate systems. LLM bots now crawl 3.6× Googlebot's volume (SEJ, Apr 2026).",
        trend: "up",
        cred: "research",
        ref: "https://www.position.digital/blog/ai-seo-statistics/",
      },
      {
        cat: "Authority",
        item: "E-E-A-T",
        note: "Experience / Expertise / Authoritativeness / Trustworthiness composite signals",
        update: "Fan-Out Effect study inversely confirms: DA shows no positive correlation with AI citation rate. Always-cited pages average DA 53 vs. never-cited pages DA 56. E-E-A-T remains important for Google SEO, but traditional DA metrics do not transfer to AI citation.",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
    ],

    GEO: [
      {
        cat: "Platform Presence",
        item: "YouTube",
        note: "Product demos and tutorials with real on-camera presence provide hard-to-fabricate authenticity signals",
        update: "Q1 2026: YouTube surpassed Reddit as #1 LLM citation domain (~16% of AI answers, GEORaiser). Fan-Out study: YouTube DA 100 but only 2.4% citation rate — proving high DA alone doesn't guarantee citation; page structure still matters.",
        trend: "up",
        cred: "opinion",
        ref: "https://georaiser.com/blog/youtube-overtakes-reddit-ai-citations",
      },
      {
        cat: "Platform Presence",
        item: "LinkedIn (Long-form Articles)",
        note: "LinkedIn articles (not short posts) deliver significantly stronger AI citation impact for B2B brands",
        update: "LinkedIn rose from rank 11 to rank 5 in ChatGPT citation rankings over 3 months (GEORaiser). LinkedIn articles account for 50–66% of all LinkedIn AI citations.",
        trend: "up",
        cred: "opinion",
        ref: "https://georaiser.com/blog/youtube-overtakes-reddit-ai-citations",
      },
      {
        cat: "Platform Presence",
        item: "Reddit",
        note: "Authentic community discussion; still high-value for Perplexity and Google AI Overview",
        update: "Reddit is a core part of GPT-5.3's citation pool (Writesonic, Mar 2026). GPT-5.4 Thinking relies on it much less. Perplexity and Google AI Overview Reddit citations remain stable. Cross-model strategy requires differentiation.",
        trend: "stable",
        cred: "opinion",
        ref: "https://www.bradleebartlett.com/blog/gpt-5-4-citation-study-chatgpt-who-gets-cited",
      },
      {
        cat: "Platform Presence",
        item: "Google AI Mode",
        note: "Google's conversational AI search experience, embedded in Chrome and Android",
        update: "AI Overviews and AI Mode share only 13.7% cited URL overlap — separate optimization strategies required. 93% of Google AI Mode searches are zero-click (ALM Corp, 2026). ⚠️ Some cited figures lack complete source attribution.",
        trend: "up",
        cred: "official",
        ref: "https://techcrunch.com/2026/04/16/google-now-lets-you-explore-the-web-side-by-side-with-ai-mode/",
      },
      {
        cat: "Content Strategy",
        item: "Fan-out Coverage Strategy",
        note: "For ChatGPT: 26–50% sub-query coverage outperforms 100% comprehensive coverage; focus beats breadth",
        update: "🆕 AirOps + Kevin Indig study (Apr 2026) establishes: 26–50% fan-out coverage (38.2%) beats 100% (34.0%); optimal word count 500–2,000; optimal subheadings 7–20. ⚠️ ChatGPT / Bing pipeline only.",
        trend: "up",
        cred: "research",
        ref: "https://www.airops.com/report/the-fan-out-effect-what-happens-between-a-query-and-a-citation",
      },
      {
        cat: "Measurement",
        item: "AI Traffic Share / Brand Mention Rate",
        note: "Track brand citation frequency and mention rates across AI platforms",
        update: "Post GPT-5.3 switch: citation domains per response down 20% (Resoneo, Apr 2026); GPT-5.3 and GPT-5.4 share only 7% citation overlap (Writesonic). With rapid model upgrades (GPT-5.5 on Apr 23), re-test baseline queries monthly. 35% of ChatGPT queries trigger live web search (Superlines, Apr 2026).",
        trend: "down",
        cred: "research",
        ref: "https://www.searchenginejournal.com/chatgpt-search-is-citing-fewer-sites-data-shows/571219/",
      },
      {
        cat: "Tools",
        item: "Lumar AI Visibility / Cloudflare AI Crawler Management",
        note: "New tools for tracking AI citations and managing AI crawler access",
        update: "🆕 Lumar launched AI Visibility tools tracking brand presence, sentiment, and citation sources across AI models with actionable gap analysis. Cloudflare new feature: automatically converts canonical tags to 301 redirects for AI training bots (GPTBot, ClaudeBot), reducing duplicate content ingestion without affecting AI assistants.",
        trend: "up",
        cred: "opinion",
        ref: "https://www.lumar.io/blog/industry-news/seo-ai-search-industry-news-april-2026/",
      },
    ],

    SEO: [
      {
        cat: "Algorithm",
        item: "Core Updates",
        note: "Major broad ranking re-evaluations, 1–2 per quarter, focused on site-wide quality signals",
        update: "March 2026 Core Update (3/27–4/8) complete: 79.5% top-3 URL churn (SE Ranking); 'destination source' gains and 'intermediary' losses pattern confirmed (Aleyda Solis, Sistrix).",
        trend: "stable",
        cred: "research",
        ref: "https://searchengineland.com/march-2026-google-core-update-what-changed-474397",
      },
      {
        cat: "Algorithm",
        item: "Spam Updates",
        note: "Standalone updates targeting link manipulation and scaled low-quality content",
        update: "SEO community reporting a surge in URL deindexing since early April 2026; raised publicly by former Google employee Pedro Dias. John Mueller: 'nothing exceptional.' Prevailing theory: index quality filtering intensified as AI-generated content floods the web. ⚠️ Not officially confirmed.",
        trend: "up",
        cred: "opinion",
        ref: "https://www.seroundtable.com/category/google-updates",
      },
      {
        cat: "Traffic",
        item: "AI Overview CTR Impact",
        note: "Queries with AI Overviews show significantly lower traditional organic CTR",
        update: "AI Overview queries: CTR down 61% (Seer Interactive, Apr 2026). Pages cited within AI Overviews receive ~120% more clicks per impression than uncited pages. 93% of Google AI Mode searches are zero-click (ALM Corp).",
        trend: "down",
        cred: "research",
        ref: "https://ahrefs.com/blog/ai-overviews-reduce-clicks-update/",
      },
      {
        cat: "Ranking Signals",
        item: "Page-level Authority / Destination Brand",
        note: "Brand sites, official institutions, and specialist publishers' 'destination value' is a core ranking differentiator",
        update: "Fan-Out Effect study confirms from the AI angle: DA cannot predict AI citations. Preferred Sources (global rollout Apr 30) adds explicit user preference as a Top Stories signal — 'being remembered' and 'being chosen' are now competitive dimensions.",
        trend: "up",
        cred: "research",
        ref: "https://searchengineland.com/march-2026-google-core-update-what-changed-474397",
      },
      {
        cat: "Ranking Signals",
        item: "Preferred Sources (User Preference Signal)",
        note: "User-declared publisher preferences used as a Top Stories and Google Discover ranking signal",
        update: "🆕 Global rollout across all supported languages on April 30, 2026 (official confirmation). Marked sources: 2× CTR lift. 200,000+ sites selected globally. Button assets in 16 languages provided by Google.",
        trend: "up",
        cred: "official",
        ref: "https://searchengineland.com/google-preferred-sources-now-works-for-all-languages-476051",
      },
    ],
  },
};
